spring:
  application:
    name: spring-auth-api
  datasource:
    url: jdbc:postgresql://192.168.0.99:5432/auth-api
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
